### ISSUE TITLE
Add a type for intents which are not component specific

### ISSUE THREAD

**Issue by poojamaniar** [cockroachdb/ui#146]
Badge, Avatar, and InlineAlerts all have different Intents -refer to [Figma](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System?node-id=46%3A3634). Currently InlineAlerts is pulling an intent type from Icon, but ideally the Intent type would also be defined for components.

**Comment by nathanstilwell** [comment]
fixed by #182
