### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#21]
# Button
> Cockroach Core Components Candidate

A UI element that a user can select to perform an action. While buttons can have _intents_ to express intention, this component should be purely [_presentational_](https://redux.js.org/basics/usage-with-react/#presentational-and-container-components) and contain no state or perform no action of its own. This component will be composed into other components and so should remain completely naive.
 
![Screen Shot 2020-04-08 at 18 21 55](https://user-images.githubusercontent.com/397448/78839160-da86b180-79c5-11ea-83fb-5c8d6d3d3660.png)

### `Intent`

From designs it seems that we have three _intents_, *Primary*, *Secondary*, and *Flat*.
![Screen Shot 2020-04-23 at 17 34 40](https://user-images.githubusercontent.com/397448/80151904-c1b2fa00-8588-11ea-8028-5dd0164a4172.png)
![Screen Shot 2020-04-23 at 17 34 44](https://user-images.githubusercontent.com/397448/80151915-c4adea80-8588-11ea-8dee-4b5e7a414b71.png)
![Screen Shot 2020-04-23 at 17 34 48](https://user-images.githubusercontent.com/397448/80151922-c7104480-8588-11ea-9398-922894aefd54.png)

### `Tint`

Inside of these _intents_, we occasionally have apply a color (or tint) to augment the meaning of the button, but this doesn't change it's intention. Some examples,

![Screen Shot 2020-04-23 at 17 36 48](https://user-images.githubusercontent.com/397448/80152153-29694500-8589-11ea-98e0-853fcc37d1c3.png)
![Screen Shot 2020-04-23 at 17 37 01](https://user-images.githubusercontent.com/397448/80152165-2ff7bc80-8589-11ea-9e1f-bed632d661d2.png)
![Screen Shot 2020-04-23 at 17 37 10](https://user-images.githubusercontent.com/397448/80152169-31c18000-8589-11ea-95ef-397306078a0b.png)

💭 _I'm not sure if all of these are use cases, but the "danger" or "red" tint is certainly a use case that exists and I can image other cases where we may employ standard colors to alter primary or secondary buttons._

### `Size`

There are two sizes defined that seemed be used pretty widely, "default" and "small".

![Screen Shot 2020-04-23 at 17 44 06](https://user-images.githubusercontent.com/397448/80152666-1c992100-858a-11ea-8ad8-b725281d27c7.png)

This only seems to apply to height. In terms of width ...

### Fluid Width

Button widths seem to fall into two categories, _width based on content_ and _width based on container_.

*Based on content*
![Screen Shot 2020-04-23 at 17 36 48](https://user-images.githubusercontent.com/397448/80152833-66820700-858a-11ea-9ad0-990f4f798f65.png)
![Screen Shot 2020-04-23 at 17 47 02](https://user-images.githubusercontent.com/397448/80152924-95987880-858a-11ea-8fdb-607a23c1d5e7.png)
![Screen Shot 2020-04-23 at 17 47 09](https://user-images.githubusercontent.com/397448/80152925-96310f00-858a-11ea-862f-a2f8cf8919ef.png)
![Screen Shot 2020-04-23 at 17 47 51](https://user-images.githubusercontent.com/397448/80152926-96310f00-858a-11ea-9220-82f288b1672d.png)

*Based on container*
![Screen Shot 2020-04-23 at 17 48 58](https://user-images.githubusercontent.com/397448/80153099-ea3bf380-858a-11ea-9bb7-abea9501f0fb.png)
![Screen Shot 2020-04-23 at 17 49 03](https://user-images.githubusercontent.com/397448/80153100-ead48a00-858a-11ea-93cf-f4ba6bfcc594.png)
![Screen Shot 2020-04-23 at 17 49 34](https://user-images.githubusercontent.com/397448/80153101-ead48a00-858a-11ea-8e39-652c30d5045d.png)
![Screen Shot 2020-04-23 at 17 50 15](https://user-images.githubusercontent.com/397448/80153102-ead48a00-858a-11ea-878b-417a9923d0e4.png)

💭 ❓ _My initial thought was "Fluid" as it's a prop I've used before as a boolean prop, which is not my favorite. I'm open to ideas here for a prop names that we could use for two distinct values. Either "default" and "fluid" or "content" and "container"._

### Icons

Buttons use icons in a few different ways. To highlight content or communicate functionality by having an icon to the right or the left of the text content,

![Screen Shot 2020-04-23 at 18 26 05](https://user-images.githubusercontent.com/397448/80155769-6be25000-8590-11ea-950f-9c8a23182cef.png)

or as the content,

![Screen Shot 2020-04-23 at 18 30 26](https://user-images.githubusercontent.com/397448/80155879-9d5b1b80-8590-11ea-847c-810bde3ab9ca.png)
![Screen Shot 2020-04-23 at 18 30 31](https://user-images.githubusercontent.com/397448/80155880-9df3b200-8590-11ea-8a78-7abdaa23d77b.png)
![Screen Shot 2020-04-23 at 18 30 56](https://user-images.githubusercontent.com/397448/80155881-9df3b200-8590-11ea-8add-3969a82ce6b2.png)

💭 ❓ _One thing we may need council from design on, is if the icons are always part of the content or if they will have a layout different from the content. In the first case we may not need to include knowledge of icons at all in the implementation of button and could get away with `<Button><Icon /> Content</Button>`. If the icon needs alignment apart from the content (as seen often when buttons are used as trigger for menus) we have need something like `<Button iconLeft={Icon} iconRight={Icon}>Content</Button>`. Even in this case an "IconButton" would just not use these props and provide an Icon as content, e.g. `<Button>{Icon}</Button>`_

#### `Button` from [AntD](https://ant.design/components/button/)

```jsx
export interface BaseButtonProps {
  type?: ButtonType;
  icon?: React.ReactNode;
  shape?: ButtonShape;
  size?: SizeType;
  loading?: boolean | { delay?: number };
  prefixCls?: string;
  className?: string;
  ghost?: boolean;
  danger?: boolean;
  block?: boolean;
  children?: React.ReactNode;
}
```

#### `Button` from `[cockroachdb/cockroach](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/ui/src/components/button/button.tsx)

```jsx
export interface ButtonProps {
  type?: "primary" | "secondary" | "flat";
  disabled?: boolean;
  size?: "default" | "small";
  children?: React.ReactNode;
  icon?: () => React.ReactNode;
  iconPosition?: "left" | "right";
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
  className?: string;
}
```

#### `Button` from CockroachCloud
```jsx
interface ButtonProps {
  category: ButtonCategory;
  actionType?: ButtonActionType;
  id?: string;
  className?: string;
  text?: string;
  href?: string; // external link
  to?: string; // internal link
  download?: string;
  small?: boolean;
  icon?: React.ReactNode;
  iconPosition?: ButtonIconPosition;
  disabled?: boolean;
  fluid?: boolean;
  onClick?: (...params: any) => any;
}
```

**Comment by Annebirzin** [comment]
For reference, adding a Figma link of the Button audit which demonstrates examples of where buttons appear across CockroachCloud and Admin UI: 

[Button Audit](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1349%3A3555)
