### ISSUE TITLE
Avatar Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#22]
# Avatar
> Cockroach Core Components Candidate

 _A temporary manifestation or aspect of a continuing entity._ Avatars are iconic representations of a user, organization, action, step in progression, or result.

![Screen Shot 2020-04-08 at 18 10 37](https://user-images.githubusercontent.com/397448/78838494-4e27bf00-79c4-11ea-8ee3-4c27e77bbaa4.png)

### Existing Components
- `UserAvatar` from [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/ui/src/views/shared/components/userAvatar/index.tsx)
- `Avatar` from CockroachCloud

**Comment by koorosh** [comment]
It fills like `Steps` and `Validation` components (shown on the attached screenshot) have to be stand-alone components because they have very little in common with Avatars.

**Comment by nathanstilwell** [comment]
@koorosh I think that is true that `<Avatar>` shouldn't fully encapsulate the functionality of steps or validation, but I think those components could use `<Avatar>` as a dependency.
