### ISSUE TITLE
Input Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#23]
# Input
> Cockroach Core Components Candidate

A control allowing the user to enter text by typing or interacting with other controls. This component should be concerned with extensibility over state management.

![Screen Shot 2020-04-08 at 18 37 52](https://user-images.githubusercontent.com/397448/78840176-13278a80-79c8-11ea-80db-a22a7485fe03.png)

_**There's kind of a lot going on here, but I think this component needs a name to suggest it will support composition into other controls. This could serve as the base for text input, select menus, password or email input fields, etc_

### Existing Components
- [`TextInput`](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/ui/src/components/textInput/index.tsx), [`Search`](https://github.com/cockroachdb/cockroach/blob/27debe8006fc99a8e9db9bae6407796a2d6e6f23/pkg/ui/src/views/app/components/Search/index.tsx) from [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach)
- `InputField`, `TextInput`, `ValidatedInput` and `Input` from CockroachCloud

**Comment by Annebirzin** [comment]
For reference, adding a Figma link of the Input audit which demonstrates examples of where inputs appear across CockroachCloud and Admin UI:

[Input Audit](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1359%3A3177)
