### ISSUE TITLE
Modal Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#24]
# Modal
> Cockroach Core Components Candidate

A display component focusing the user's attention on interstitial information

![Screen Shot 2020-04-09 at 13 56 00](https://user-images.githubusercontent.com/397448/78925706-df04a600-7a69-11ea-998f-026d5f555c5f.png)

### Existing Components
- `Modal` from [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/components/modal/modal.tsx) (based on `Modal` from [AntD](https://ant.design/components/modal/))
- `Modal` from CockroachCloud (based on `Modal` from [AntD](https://ant.design/components/modal/))
- `CustomModal` from [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/app/components/modal/index.tsx) (based on `Modal` from [AntD](https://ant.design/components/modal/))

**Comment by Annebirzin** [comment]
For reference, adding a Figma link of the Modal audit which demonstrates examples of where inputs appear across CockroachCloud and Admin UI: 

[Modal Audit](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1415%3A1)

**Comment by laurenbarker** [comment]
I think we should consider using https://github.com/reactjs/react-modal for the modal functionality. Our current modals are not accessible and cannot be focused on by screen readers.
