### ISSUE TITLE
Tooltip Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#25]
# Tooltip
> Cockroach Core Components Candidate

An arbitrarily positioned element providing more information about another UI element

![Screen Shot 2020-04-09 at 14 10 20](https://user-images.githubusercontent.com/397448/78926878-df05a580-7a6b-11ea-880b-f49ec3a01b99.png)

### Existing Components
- `Tooltip` from cockroachdb/cockroach
- `HoverText` from CockroachCloud
- `InfoBox` from CockroachCloud
- `Tooltip` from AndD

**Comment by Annebirzin** [comment]
For reference, below is a Figma link of the Tooltip audit which demonstrates examples of where inputs appear across CockroachCloud and Admin UI: 

[Tooltip Audit](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1415%3A58)
