### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#26]
# Dropdown
> Cockroach Core Components Candidate

A target element with a floating menu to aid in selecting input by the user

![Screen Shot 2020-04-09 at 14 22 02](https://user-images.githubusercontent.com/397448/78927816-80d9c200-7a6d-11ea-86a4-55913316d764.png)

### Existing Components
-  [`Dropown`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/components/dropdown/dropdown.tsx), [`Dropdown`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/shared/components/dropdown/index.tsx), [`Select`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/components/select/select.tsx) from cockroachdb/cockroach
- `Select` and `SelectInput` from CockroachCloud

**Comment by Annebirzin** [comment]
For reference, below is a Figma link of the Dropdown audit which demonstrates examples of where dropdowns appear across CockroachCloud and Admin UI:

[Dropdown audit](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1398%3A1)
