### ISSUE TITLE
Link Component

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#39]
# Link
> Cockroach Core Components Candidate

A UI element that is used to change the URL

![Screen Shot 2020-04-23 at 18 47 35](https://user-images.githubusercontent.com/397448/80156914-0b084700-8593-11ea-8f59-20a342e1f0ad.png)

*Examples*
![Screen Shot 2020-04-23 at 18 48 22](https://user-images.githubusercontent.com/397448/80156923-12c7eb80-8593-11ea-96b1-ccfa8277f752.png)
![Screen Shot 2020-04-23 at 18 48 28](https://user-images.githubusercontent.com/397448/80156924-13608200-8593-11ea-8708-235b7e0f2697.png)

💭 ❗ 

So the more I think about this one, I **don't think this should be a component** in our design system. While I think we can dedicate design resources to defining what they should _look like_, routing inside an application isn't something core components should have an opinion about. So why am I making an issue for **not** creating a component? Because I think we speak to this explicitly in either our Button documentation (when talking about "Flat Buttons") or somewhere in the design system.

**Comment by jeremycbloom** [comment]
That works for me @nathanstilwell . cc @Annebirzin

**Comment by Annebirzin** [comment]
Yep makes sense to me 👍

**Comment by nathanstilwell** [comment]
What about

```
<Link 
  onClick={() => void}
  text={text}
/>
```

I think this is a good place to start.

**Comment by tharun208** [comment]
@nathanstilwell, I like to work on this
